Write-Host "`nGit Readme Builder - GReadr v1.0! By Owen Steele (c) 2021"
Write-Host "Find greadr on github: https://github.com/OwenSteele/greadr"
Write-Host "GReadr is built in PowerShell and GoLang"
Write-Host "The Files are managed in powershell, with the mapped files written in Go"
Write-Host "`n --- Planned Updates ---"
Write-Host "    Write powershell in .cmd/.sh languages too"
Write-Host "    Introduce alternative to Go, using only powershell/bash"
Write-Host "    Addtional features: increased options in config files, more templates, increased optional args in greader calls"
Write-Host ""